source 'https://rubygems.org'
ruby '2.0.0'

gem 'data_mapper'
gem 'dm-mysql-adapter'
gem 'dm-redis-adapter'
gem 'foreman'
gem 'haml'
gem 'json'
gem 'multi_json'
gem 'oauth'
gem 'omniauth'
gem 'omniauth-tumblr'
gem 'redcarpet'
gem 'ruby-bbcode'
gem 'sinatra'
gem 'thin'
gem 'tumblr_client'
