<?php
// $Id: $

/**
 * @file
 * Enable comics module.
 */

/**
 * Implementation of hook_menu().
 */
function comics_menu()
{
  $items['comics'] = array(
    'title' => 'Daily Comics',
    'page callback' => 'comics_all',
    'access arguments' => comics_perm(),
  );
  return $items;
}

/**
 * Implementation of hook_info().
 */
function comics_info() {
  return t('The Web Comic defines a new node type for display of web-based comics, which can be created at !link.', array('!link' => l(t('node/add/comics'), 'node/add/comics')));
}

/**
 * Implementation of hook_node_info().
 */
function comics_node_info() {
  return array(
    'comics' => array(
      'name' => t('Web Comic'),
      'module' => 'comics',
      'description' => t("A Web Comic is stolen content."),
      'has_title' => TRUE,
      'title_label' => t('Comic Name'),
      'has_body' => FALSE,
    )
  );
}


/**
 * Implementation of hook_help().
 */
function comics_help($path, $arg) {
  switch ($path) {
    case 'admin/modules#description':
      return t('A module for retrieving \'net comics');

    case 'node/add#comics':
      return t('This is a comics node which requires some special data.');
  }
}  

/**
 * Implementation of hook_access().
 */
function comics_access($op, $node, $account) {

  if ($op == 'create') {
    return user_access('create a comic', $account);
  }

  if ($op == 'update' || $op == 'delete') {
    if (user_access('edit own comic', $account) && ($account->uid == $node->uid)) {
       return TRUE;    
    }
  }

  if ($op == 'view') {
    return TRUE;
  }
}


/**
 * Implementation of hook_node_perm().
 */
function comics_perm() {
  return array(
    'access comics',
    'create a comic',
    'edit own comic'
  );
}

/**
 * Implementation of hook_form().
 */
function comics_form(&$node, $form_state)
{
  $type = node_get_types('type', $node);

  if ($type->has_title) {
    $form['title'] = array(
      '#type' => 'textfield',
      '#title' => check_plain($type->title_label),
      '#required' => FALSE,
      '#default_value' => $node->title
    );
  }


  if ($type->has_body) {
    $form['body'] = node_body_field($node, $type->body_label, $type->min_word_count);
  }

  $form['urlname'] = array(
    '#type' => 'textfield',
    '#title' => t('URL name'),
    '#default_value' => $node->urlname,
  );

  $form['imgname'] = array(
    '#type' => 'textfield',
    '#title' => t('IMG name'),
    '#default_value' => $node->imgname,
  );

  return $form;
}

/**
 * Implementation of hook_validate().
 */
function comics_validate($node, &$form) {
  // do nothing
}

/**
 * Implementation of hook_insert().
 */
function comics_insert($node) {
  db_query("INSERT INTO {comics} (nid, urlname, imgname) VALUES (%d, '%s', '%s')", $node->nid, $node->urlname, $node->imgname);
}

/**
 * Implementation of hook_udpate().
 */
function comics_update($node) {
  db_query("UPDATE {comics} SET urlname = '%s', imgname = '%s' WHERE nid = %d", $node->urlname, $node->imgname, $node->nid);
}

/**
 * Implementation of hook_delete().
 */
function comics_delete($node) {
  db_query("DELETE FROM {comics} WHERE nid = %d", $node->nid);
}

/**
 * Implementation of hook_load().
 */
function comics_load($node) {
  $t = db_fetch_object(db_query('SELECT urlname, imgname FROM {comics} WHERE nid = %d', $node->nid)); 

  return $t;
}

/**
 * Implementation of hook_view().
 */
function comics_view($node, $teaser = FALSE, $page = FALSE) {
  $node = node_prepare($node, $teaser);  
  $node->content['comic'] = array(
    '#value' => theme('comics_show', $node),
    '#weight' => 1,
  );

  return $node;
}

function comics_theme() {
  return array(
    'comics_show' => array(
      'arguments' => array('node'),
    ),
  );
}

function theme_comics_show($node) {   
  $output = '<div class="comics_show">';
  
  if ($node->title == 'Zippy the Pinhead') {
    $url = 'http://zippythepinhead.com';
    $imglink = 'http://zippythepinhead.com/Merchant2/graphics/00000001/';

    $tm = localtime();

    $yyyy = $tm[5] + 1900;
    $yy = $tm[5] - 100;
    $mm = $tm[4] + 1;
    $dd = $tm[3];

    if ($yy < 10) {
      $yy = "0". $yy;
    }

    if ($mm < 10) {
      $mm = "0". $mm;
    }

    if ($dd < 10) {
      $dd = "0". $dd;
    }

    $imglink .= $yyyy;
    $imglink .= '/images/'.$mm.$dd.$yy.'.gif';

    $output .= '<a href="'.$url.'">';
    $output .= '<img src="'.$imglink.'">';
    $output .= '</a>';

  } else if ($node->title == 'XKCD') {
    $url = 'http://xkcd.com';
    $imglink .= 'http://imgs.xkcd.com';

    $response = file_get_contents($url);

    $output .= '<a href="'.$url.'">';
    
    $r = preg_split('/\n/', $response);

    $pattern1 = '/Image URL/';
    $pattern2 = '/comics\/(.*\.png)/';

    for ($ii = 0; $ii < count($r); $ii++) {
      $line = $r[$ii];

      if (preg_match($pattern1, $line, $match1)) {
        if (preg_match($pattern2, $line, $match2)) {
          $output .= '<img src="'.$imglink.'/'.$match2[0].'">';

        }
      }
    }

    $output .= '</a>';
    
  } else if ($node->imgname == '') {
    $today = getdate();
   
    $mon = $today['mon'];

    if (strlen($mon) == 1) {
      $mon = "0" . $mon;
    }

    $url = 'http://comics.com/'.$node->urlname.'/'.$today['year'].'-'.$mon.'-'.$today['mday'];
    
    $response = file_get_contents($url);

    $output .= "Searching... " . $url;

    $output .= '<a href="'.$url.'">';

    $r = preg_split('/\n/', $response);
    
    $url = preg_split('/\//', $node->urlname);
    $uNum = 0;

    if (2 == count($url)) {
	  $uNum = 1;
    }

    $pattern1 = '/class="STR_StripImage"/';
    $pattern2 = '/src=\"(.*)\"/';

    for ($ii = 0; $ii < count($r); $ii++) {
      $line = $r[$ii];

      if (preg_match($pattern1, $line, $match1)) {
        $output .= $line;
      }
    } 

    $output .= '</a>';
  } else {
    $tm = localtime();

    $yyyy = $tm[5] + 1900;
    $yy = $tm[5] - 100;
    $mm = $tm[4] + 1;
    $dd = $tm[3];

    if ($yy < 10) {
      $yy = "0". $yy;
    }

    if ($mm < 10) {
      $mm = "0". $mm;
    }

    if ($dd < 10) {
      $dd = "0". $dd;
    }

    $url = "http://www.ucomics.com/".$node->urlname;
    $imglink = "http://images.ucomics.com/comics/".$node->imgname."/";
    $imglink .= $yyyy."/".$node->imgname.$yy.$mm.$dd.".gif";

    $output .= '<a href="'.$url.'">';
    $output .= '<img src="'.$imglink.'">';
    $output .= '</a>';

  }

  $output .= '</div>';

  return $output;
}

function comics_all() {
  $comics = array();
  
  $_comics = db_query("SELECT nid FROM {comics}"); 

  $ii = 0;
  while ($c = db_fetch_array($_comics)) {
    $comic = db_fetch_object(db_query("SELECT node.nid, node.title, urlname, imgname FROM {node}, {comics} WHERE node.nid = comics.nid AND node.nid = %d ORDER BY node.title ASC", $c['nid']));

    $comics[++$ii] = $comic;
  }

  $result = pager_query('SELECT DISTINCT(n.nid), n.sticky, n.created FROM {node n} WHERE n.type = \'comics\' AND n.promote = 1 AND n.status = 1 ORDER BY n.sticky DESC, n.created ASC ', variable_get('default_nodes_main', 20));

  $output = '<div id="comics">';
  $output .= '<ul>';

  if (user_access('create a comic')) {
    $output .= '<li>'.l(t('create a new comic'), "node/add/comics");
  }

  $output .= '</ul>';

  if (db_result(db_query("SELECT COUNT(*) FROM {node} WHERE type = 'comics' AND promote = 1 and status = 1"))) {
    drupal_set_html_head('<link rel="alternate" type="application/rss+xml" title="RSS" href="'. url('node/feed', array('absolute' => TRUE)) .'" />');

    while ($node = db_fetch_object($result)) {
      $output .= $node->nid;
      $node = node_prepare($node, FALSE);
      $output .= theme('comics_show', $node);
    }

    $output .= theme('pager', NULL, variable_get('default_nodes_main', 10));
  }

  $output .= '</div>';

  print theme('page', $output, 'Daily Comics');
}

?>
